# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rlr58e88xKTJjO7lZnKZCfsyvlHN6py
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# Global parameter (used in the model)
beta = 0.05

# Dimensionless model (standard simplified Semenov-type for thermal runaway)
def dtheta_dtau(theta, tau, Se):
    """dθ/dτ = exp(θ/(1+βθ)) - θ/Se
       Se = cooling parameter (higher Se → poorer cooling → more avalanches)"""
    return np.exp(theta / (1 + beta * theta)) - theta / Se

def simulate_one_run(Se, theta0, tmax=50, npoints=1000):
    t = np.linspace(0, tmax, npoints)
    sol = odeint(dtheta_dtau, theta0, t, args=(Se,))
    theta = sol[:, 0]
    max_theta = np.max(theta)
    # Avalanche size = excess temperature integral if runaway occurs
    if max_theta > 5.0:  # runaway threshold
        excess = np.maximum(theta - 2.0, 0)
        size = np.trapz(excess, t)
    else:
        size = 0.0
    return max_theta, size, t, theta

# Monte Carlo simulation
np.random.seed(42)
N_sim = 500
Se = 0.92                  # near-critical value (connectivity tuning)
noise_sigma = 0.08         # noise level
sizes = []
max_thetas = []
example_trajs = []

print("Running Monte Carlo simulations...")
for i in range(N_sim):
    theta0 = np.random.normal(0.0, noise_sigma)
    max_th, size, t, theta = simulate_one_run(Se, theta0)
    sizes.append(size)
    max_thetas.append(max_th)
    if i < 5:  # save a few example trajectories
        example_trajs.append((t, theta, theta0))

sizes = np.array(sizes)
positive_sizes = sizes[sizes > 0]

# Results
print(f"Runaway events: {len(positive_sizes)} / {N_sim} ({len(positive_sizes)/N_sim*100:.1f}%)")
print(f"Mean avalanche size: {positive_sizes.mean():.2f}")

# Plot 1: Example trajectories
plt.figure(figsize=(8,5))
for t, theta, th0 in example_trajs:
    plt.plot(t, theta, label=f"θ₀={th0:.3f}")
plt.axhline(5, color='r', ls='--', label='Runaway threshold')
plt.xlabel('Dimensionless time τ')
plt.ylabel('Dimensionless temperature θ')
plt.title('Example temperature trajectories (noise-driven)')
plt.legend()
plt.grid(True)
plt.savefig('example_trajectories.png', dpi=300, bbox_inches='tight')

# Plot 2: Avalanche size distribution + power-law fit
plt.figure(figsize=(8,5))
hist, bins = np.histogram(positive_sizes, bins=30, density=True)
bin_centers = (bins[:-1] + bins[1:]) / 2
plt.loglog(bin_centers, hist, 'o', label='Data')
# Simple power-law fit (log-log linear regression)
mask = hist > 0
log_bins = np.log(bin_centers[mask])
log_hist = np.log(hist[mask])
slope, intercept = np.polyfit(log_bins, log_hist, 1)
plt.loglog(bin_centers, np.exp(intercept) * bin_centers**slope, '--',
           label=f'Power law fit (α ≈ {-slope:.2f})')
plt.xlabel('Avalanche size s')
plt.ylabel('Frequency P(s)')
plt.title('Frequency distribution of avalanches (near-critical Se)')
plt.legend()
plt.grid(True, which='both')
plt.savefig('avalanche_distribution.png', dpi=300, bbox_inches='tight')

# Plot 3: Effect of connectivity (different Se)
Se_values = [0.85, 0.92, 1.05]
mean_sizes = []
for Se_test in Se_values:
    sizes_test = []
    for _ in range(200):
        theta0 = np.random.normal(0.0, noise_sigma)
        _, size, _, _ = simulate_one_run(Se_test, theta0)
        sizes_test.append(size)
    mean_sizes.append(np.mean([s for s in sizes_test if s > 0]) if any(s > 0 for s in sizes_test) else 0)
plt.figure(figsize=(6,4))
plt.plot(Se_values, mean_sizes, 'o-')
plt.xlabel('Connectivity parameter Se (higher = poorer cooling)')
plt.ylabel('Mean avalanche size')
plt.title('Effect of connectivity on avalanche magnitude')
plt.grid(True)
plt.savefig('connectivity_effect.png', dpi=300, bbox_inches='tight')

print("\nPlots saved successfully:")
print(" - example_trajectories.png")
print(" - avalanche_distribution.png")
print(" - connectivity_effect.png")
print("\nProject code is now ready for GitHub!")